# -*- coding: utf-8 -*-
"""대학원 신입생 세미나 5주차 과제(2024-26271 황주영).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11b74IP_kd0fvfHsJbYp0O4Eugodz0A_4
"""

import matplotlib.pyplot as plt
import numpy as np

def trap_rain_water_visualized(heights):
    if not heights or len(heights) < 3:
        return 0  # 물이 고일 수 없음

    n = len(heights)
    left_max = [0] * n
    right_max = [0] * n
    water = [0] * n  # 각 위치에서 고일 수 있는 물의 양

    # 왼쪽에서 최고 높이 계산
    left_max[0] = heights[0]
    for i in range(1, n):
        left_max[i] = max(left_max[i - 1], heights[i])

    # 오른쪽에서 최고 높이 계산
    right_max[n - 1] = heights[n - 1]
    for i in range(n - 2, -1, -1):
        right_max[i] = max(right_max[i + 1], heights[i])

    # 각 위치에서 고일 수 있는 물의 양 계산
    total_water = 0
    for i in range(n):
        water[i] = max(0, min(left_max[i], right_max[i]) - heights[i])
        total_water += water[i]

    # ---- 그림 그리기 ----
    x = np.arange(n)  # x 좌표

    fig, ax = plt.subplots(figsize=(10, 6))

    # 바 그래프 그리기
    ax.bar(x, heights, color='black', alpha=0.7, label='ground',width=1)  # 벽
    ax.bar(x, water, bottom=heights, color='blue', alpha=0.6, label='water',width=1)  # 물

    # 제목 및 레이블
    ax.set_title(f'Trapped water: {total_water}', fontsize=14)
    ax.set_xlabel('Index', fontsize=12)
    ax.set_ylabel('Height', fontsize=12)
    ax.legend()
    ax.set_xticks(range(n))

    plt.show()

    return total_water

# 예제 실행
heights1 = [0,1,0,2,1,0,1,3,2,1,2,1]
trap_rain_water_visualized(heights1)

heights2 = [4,2,0,3,2,5]
trap_rain_water_visualized(heights2)

heights3 = [5,4,1,2,1,4,5]
trap_rain_water_visualized(heights3)